//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_OrgUnitHierarchy
    {
        public string OrgUnitID { get; set; }
        public string ParentID { get; set; }
        public string OrgUnitName { get; set; }
        public int Lvl { get; set; }
        public string Lvl1ID { get; set; }
        public string Lvl2ID { get; set; }
        public string Lvl3ID { get; set; }
        public string Lvl4ID { get; set; }
        public string Lvl5ID { get; set; }
        public string Lvl6ID { get; set; }
        public string Lvl7ID { get; set; }
        public string Lvl8ID { get; set; }
        public string Lvl9ID { get; set; }
        public string Lvl10ID { get; set; }
        public string Lvl1Desc { get; set; }
        public string Lvl2Desc { get; set; }
        public string Lvl3Desc { get; set; }
        public string Lvl4Desc { get; set; }
        public string Lvl5Desc { get; set; }
        public string Lvl6Desc { get; set; }
        public string Lvl7Desc { get; set; }
        public string Lvl8Desc { get; set; }
        public string Lvl9Desc { get; set; }
        public string Lvl10Desc { get; set; }
        public string Lvl1EntityID { get; set; }
        public string Lvl2EntityID { get; set; }
        public string Lvl3EntityID { get; set; }
        public string Lvl4EntityID { get; set; }
        public string Lvl5EntityID { get; set; }
        public string Lvl6EntityID { get; set; }
        public string Lvl7EntityID { get; set; }
        public string Lvl8EntityID { get; set; }
        public string Lvl9EntityID { get; set; }
        public string Lvl10EntityID { get; set; }
        public string Lvl1EntityDesc { get; set; }
        public string Lvl2EntityDesc { get; set; }
        public string Lvl3EntityDesc { get; set; }
        public string Lvl4EntityDesc { get; set; }
        public string Lvl5EntityDesc { get; set; }
        public string Lvl6EntityDesc { get; set; }
        public string Lvl7EntityDesc { get; set; }
        public string Lvl8EntityDesc { get; set; }
        public string Lvl9EntityDesc { get; set; }
        public string Lvl10EntityDesc { get; set; }
        public string TreeOrgUnitID { get; set; }
        public string TreeEntityID { get; set; }
        public string TreeOrgUnitName { get; set; }
        public string Attribute1ID { get; set; }
        public string Attribute1Desc { get; set; }
        public string Attribute1Type { get; set; }
        public Nullable<System.DateTime> ETLCreatedDate { get; set; }
        public string ETLCreatedBy { get; set; }
    }
}
