//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PHE_ExplorationEntities : DbContext
    {
        public DB_PHE_ExplorationEntities()
            : base("name=DB_PHE_ExplorationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MD_BusinessPartner> MD_BusinessPartner { get; set; }
        public virtual DbSet<MD_ExplorationArea> MD_ExplorationArea { get; set; }
        public virtual DbSet<MD_ExplorationAsset> MD_ExplorationAsset { get; set; }
        public virtual DbSet<MD_ExplorationBasin> MD_ExplorationBasin { get; set; }
        public virtual DbSet<MD_ExplorationBlock> MD_ExplorationBlock { get; set; }
        public virtual DbSet<MD_ExplorationBlockPartner> MD_ExplorationBlockPartner { get; set; }
        public virtual DbSet<MD_ExplorationStructure> MD_ExplorationStructure { get; set; }
        public virtual DbSet<MD_ExplorationWell> MD_ExplorationWell { get; set; }
        public virtual DbSet<MD_Paramater> MD_Paramater { get; set; }
        public virtual DbSet<MD_ParamaterList> MD_ParamaterList { get; set; }
        public virtual DbSet<MP_Entity> MP_Entity { get; set; }
        public virtual DbSet<MP_xBasinCountry> MP_xBasinCountry { get; set; }
        public virtual DbSet<TX_Attachment> TX_Attachment { get; set; }
        public virtual DbSet<LG_Activity> LG_Activity { get; set; }
        public virtual DbSet<LG_ContingentResources> LG_ContingentResources { get; set; }
        public virtual DbSet<LG_Drilling> LG_Drilling { get; set; }
        public virtual DbSet<LG_Economic> LG_Economic { get; set; }
        public virtual DbSet<LG_ExplorationStructure> LG_ExplorationStructure { get; set; }
        public virtual DbSet<LG_ProsResources> LG_ProsResources { get; set; }
        public virtual DbSet<LG_ProsResourcesTarget> LG_ProsResourcesTarget { get; set; }
        public virtual DbSet<TX_ContingentResources> TX_ContingentResources { get; set; }
        public virtual DbSet<TX_Drilling> TX_Drilling { get; set; }
        public virtual DbSet<TX_Economic> TX_Economic { get; set; }
        public virtual DbSet<TX_ESDC> TX_ESDC { get; set; }
        public virtual DbSet<TX_ESDCDiscrepancy> TX_ESDCDiscrepancy { get; set; }
        public virtual DbSet<TX_ESDCForecast> TX_ESDCForecast { get; set; }
        public virtual DbSet<TX_ESDCInPlace> TX_ESDCInPlace { get; set; }
        public virtual DbSet<TX_ESDCProd> TX_ESDCProd { get; set; }
        public virtual DbSet<TX_ESDCVolumetric> TX_ESDCVolumetric { get; set; }
        public virtual DbSet<TX_ProsResources> TX_ProsResources { get; set; }
        public virtual DbSet<TX_ProsResourcesTarget> TX_ProsResourcesTarget { get; set; }
        public virtual DbSet<vw_Country> vw_Country { get; set; }
        public virtual DbSet<vw_DIM_Entity> vw_DIM_Entity { get; set; }
    }
}
