//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_ContingentResources
    {
        public string StructureHistoryID { get; set; }
        public string xStructureID { get; set; }
        public Nullable<decimal> C1COil { get; set; }
        public string C1COilUoM { get; set; }
        public Nullable<decimal> C2COil { get; set; }
        public string C2COilUoM { get; set; }
        public Nullable<decimal> C3COil { get; set; }
        public string C3COilUoM { get; set; }
        public Nullable<decimal> C1CGas { get; set; }
        public string C1CGasUoM { get; set; }
        public Nullable<decimal> C2CGas { get; set; }
        public string C2CGasUoM { get; set; }
        public Nullable<decimal> C3CGas { get; set; }
        public string C3CGasUoM { get; set; }
        public Nullable<decimal> C1CTotal { get; set; }
        public string C1CTotalUoM { get; set; }
        public Nullable<decimal> C2CTotal { get; set; }
        public string C2CTotalUoM { get; set; }
        public Nullable<decimal> C3CTotal { get; set; }
        public string C3CTotalUoM { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual LG_ExplorationStructure LG_ExplorationStructure { get; set; }
    }
}
