//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_ExplorationStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LG_ExplorationStructure()
        {
            this.LG_Drilling = new HashSet<LG_Drilling>();
            this.LG_ProsResourcesTarget = new HashSet<LG_ProsResourcesTarget>();
        }
    
        public string StructureHistoryID { get; set; }
        public string xStructureID { get; set; }
        public string xStructureName { get; set; }
        public string xStructureStatusParID { get; set; }
        public string SingleOrMultiParID { get; set; }
        public string ExplorationTypeParID { get; set; }
        public string SubholdingID { get; set; }
        public string BasinID { get; set; }
        public string RegionalID { get; set; }
        public string ZonaID { get; set; }
        public string APHID { get; set; }
        public string xAssetID { get; set; }
        public string xBlockID { get; set; }
        public string xAreaID { get; set; }
        public string UDClassificationParID { get; set; }
        public string UDSubClassificationParID { get; set; }
        public string UDSubTypeParID { get; set; }
        public string ExplorationAreaParID { get; set; }
        public string CountriesID { get; set; }
        public string Play { get; set; }
        public string StatusData { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MadamTransID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual MD_ExplorationStructure MD_ExplorationStructure { get; set; }
        public virtual LG_ContingentResources LG_ContingentResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LG_Drilling> LG_Drilling { get; set; }
        public virtual LG_Economic LG_Economic { get; set; }
        public virtual LG_ProsResources LG_ProsResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LG_ProsResourcesTarget> LG_ProsResourcesTarget { get; set; }
    }
}
