//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_ProsResourcesTarget
    {
        public string StructureHistoryID { get; set; }
        public string TargetID { get; set; }
        public string TargetName { get; set; }
        public string xStructureID { get; set; }
        public Nullable<decimal> P90InPlaceOil { get; set; }
        public string P90InPlaceOilUoM { get; set; }
        public Nullable<decimal> P50InPlaceOil { get; set; }
        public string P50InPlaceOilUoM { get; set; }
        public Nullable<decimal> PMeanInPlaceOil { get; set; }
        public string PMeanInPlaceOilUoM { get; set; }
        public Nullable<decimal> P10InPlaceOil { get; set; }
        public string P10InPlaceOilUoM { get; set; }
        public Nullable<decimal> P90InPlaceGas { get; set; }
        public string P90InPlaceGasUoM { get; set; }
        public Nullable<decimal> P50InPlaceGas { get; set; }
        public string P50InPlaceGasUoM { get; set; }
        public Nullable<decimal> PMeanInPlaceGas { get; set; }
        public string PMeanInPlaceGasUoM { get; set; }
        public Nullable<decimal> P10InPlaceGas { get; set; }
        public string P10InPlaceGasUoM { get; set; }
        public Nullable<decimal> P90InPlaceTotal { get; set; }
        public string P90InPlaceTotalUoM { get; set; }
        public Nullable<decimal> P50InPlaceTotal { get; set; }
        public string P50InPlaceTotalUoM { get; set; }
        public Nullable<decimal> PMeanInPlaceTotal { get; set; }
        public string PMeanInPlaceTotalUoM { get; set; }
        public Nullable<decimal> P10InPlaceTotal { get; set; }
        public string P10InPlaceTotalUoM { get; set; }
        public Nullable<decimal> RFOil { get; set; }
        public Nullable<decimal> RFGas { get; set; }
        public Nullable<decimal> P90RecoverableOil { get; set; }
        public string P90RecoverableOilUoM { get; set; }
        public Nullable<decimal> P50RecoverableOil { get; set; }
        public string P50RecoverableOilUoM { get; set; }
        public Nullable<decimal> PMeanRecoverableOil { get; set; }
        public string PMeanRecoverableOilUoM { get; set; }
        public Nullable<decimal> P10RecoverableOil { get; set; }
        public string P10RecoverableOilUoM { get; set; }
        public Nullable<decimal> P90RecoverableGas { get; set; }
        public string P90RecoverableGasUoM { get; set; }
        public Nullable<decimal> P50RecoverableGas { get; set; }
        public string P50RecoverableGasUoM { get; set; }
        public Nullable<decimal> PMeanRecoverableGas { get; set; }
        public string PMeanRecoverableGasUoM { get; set; }
        public Nullable<decimal> P10RecoverableGas { get; set; }
        public string P10RecoverableGasUoM { get; set; }
        public Nullable<decimal> P90RecoverableTotal { get; set; }
        public string P90RecoverableTotalUoM { get; set; }
        public Nullable<decimal> P50RecoverableTotal { get; set; }
        public string P50RecoverableTotalUoM { get; set; }
        public Nullable<decimal> PMeanRecoverableTotal { get; set; }
        public string PMeanRecoverableTotalUoM { get; set; }
        public Nullable<decimal> P10RecoverableTotal { get; set; }
        public string P10RecoverableTotalUoM { get; set; }
        public string HydrocarbonTypeParID { get; set; }
        public Nullable<decimal> GCFSR { get; set; }
        public string GCFSRUoM { get; set; }
        public Nullable<decimal> GCFTM { get; set; }
        public string GCFTMUoM { get; set; }
        public Nullable<decimal> GCFReservoir { get; set; }
        public string GCFReservoirUoM { get; set; }
        public Nullable<decimal> GCFClosure { get; set; }
        public string GCFClosureUoM { get; set; }
        public Nullable<decimal> GCFContainment { get; set; }
        public string GCFContainmentUoM { get; set; }
        public Nullable<decimal> GCFPGTotal { get; set; }
        public string GCFPGTotalUoM { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual LG_ExplorationStructure LG_ExplorationStructure { get; set; }
    }
}
