//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ExplorationBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_ExplorationBlock()
        {
            this.MD_ExplorationStructure = new HashSet<MD_ExplorationStructure>();
        }
    
        public string xBlockID { get; set; }
        public string xBlockName { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string xBlockStatusParID { get; set; }
        public string OperatorshipStatusParID { get; set; }
        public string OperatorName { get; set; }
        public string CountriesID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ExplorationStructure> MD_ExplorationStructure { get; set; }
    }
}
