//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ExplorationStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_ExplorationStructure()
        {
            this.LG_ExplorationStructure = new HashSet<LG_ExplorationStructure>();
            this.TX_ESDCDiscrepancy = new HashSet<TX_ESDCDiscrepancy>();
            this.TX_ESDCForecast = new HashSet<TX_ESDCForecast>();
            this.TX_ESDCInPlace = new HashSet<TX_ESDCInPlace>();
            this.TX_ESDCVolumetric = new HashSet<TX_ESDCVolumetric>();
        }
    
        public string xStructureID { get; set; }
        public string xStructureName { get; set; }
        public string xStructureStatusParID { get; set; }
        public string SingleOrMultiParID { get; set; }
        public string ExplorationTypeParID { get; set; }
        public string SubholdingID { get; set; }
        public string BasinID { get; set; }
        public string RegionalID { get; set; }
        public string ZonaID { get; set; }
        public string APHID { get; set; }
        public string xAssetID { get; set; }
        public string xBlockID { get; set; }
        public string xAreaID { get; set; }
        public string UDClassificationParID { get; set; }
        public string UDSubClassificationParID { get; set; }
        public string UDSubTypeParID { get; set; }
        public string ExplorationAreaParID { get; set; }
        public string CountriesID { get; set; }
        public string Play { get; set; }
        public string StatusData { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MadamTransID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MD_ExplorationAsset MD_ExplorationAsset { get; set; }
        public virtual MD_ExplorationBasin MD_ExplorationBasin { get; set; }
        public virtual MD_ExplorationBlock MD_ExplorationBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LG_ExplorationStructure> LG_ExplorationStructure { get; set; }
        public virtual TX_ESDC TX_ESDC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_ESDCDiscrepancy> TX_ESDCDiscrepancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_ESDCForecast> TX_ESDCForecast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_ESDCInPlace> TX_ESDCInPlace { get; set; }
        public virtual TX_ESDCProd TX_ESDCProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_ESDCVolumetric> TX_ESDCVolumetric { get; set; }
    }
}
