//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ExplorationWell
    {
        public string xWellID { get; set; }
        public string xWellName { get; set; }
        public string DrillingLocation { get; set; }
        public string RigTypeParID { get; set; }
        public string WellTypeParID { get; set; }
        public Nullable<decimal> BHLocationLatitude { get; set; }
        public Nullable<decimal> BHLocationLongitude { get; set; }
    }
}
