//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ExplorationBlockPartner
    {
        public string xBlockID { get; set; }
        public string PartnerID { get; set; }
        public string PartnerName { get; set; }
        public Nullable<decimal> PI { get; set; }
        public string OperatorshipStatusParID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
    }
}
