//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ParamaterList
    {
        public string Schema { get; set; }
        public string ParamID { get; set; }
        public string ParamListID { get; set; }
        public Nullable<decimal> ParamValue1 { get; set; }
        public string ParamValue1Text { get; set; }
        public Nullable<decimal> ParamValue2 { get; set; }
        public string ParamValue2Text { get; set; }
        public string ParamListDesc { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MD_Paramater MD_Paramater { get; set; }
    }
}
