//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_Entity
    {
        public int EffectiveYear { get; set; }
        public string SubholdingID { get; set; }
        public string RegionalID { get; set; }
        public string ZonaID { get; set; }
        public string xBlockID { get; set; }
        public string BasinID { get; set; }
        public string xAssetID { get; set; }
        public string APHID { get; set; }
        public string xAreaID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
