//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP_xBasinCountry
    {
        public string BasinID { get; set; }
        public string CountryID { get; set; }
        public string CountryName { get; set; }
    
        public virtual MD_ExplorationBasin MD_ExplorationBasin { get; set; }
    }
}
