//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_Attachment
    {
        public string Schema { get; set; }
        public string TransactionID { get; set; }
        public string SubTranscationID { get; set; }
        public string Menu { get; set; }
        public string PathParID { get; set; }
        public int FileID { get; set; }
        public string FileCategoryParID { get; set; }
        public string FileName { get; set; }
        public string FileNameSave { get; set; }
        public string DocumentType { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Size { get; set; }
        public string SizeUoM { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RefID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
