//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_ESDCVolumetric
    {
        public string xStructureID { get; set; }
        public string UncertaintyLevel { get; set; }
        public Nullable<decimal> GRRPrevOil { get; set; }
        public Nullable<decimal> GRRPrevCondensate { get; set; }
        public Nullable<decimal> GRRPrevAssociated { get; set; }
        public Nullable<decimal> GRRPrevNonAssociated { get; set; }
        public Nullable<decimal> ReservesPrevOil { get; set; }
        public Nullable<decimal> ReservesPrevCondensate { get; set; }
        public Nullable<decimal> ReservesPrevAssociated { get; set; }
        public Nullable<decimal> ReservesPrevNonAssociated { get; set; }
        public Nullable<decimal> GOIOil { get; set; }
        public Nullable<decimal> GOICondensate { get; set; }
        public Nullable<decimal> GOIAssociated { get; set; }
        public Nullable<decimal> GOINonAssociated { get; set; }
        public Nullable<decimal> ReservesOil { get; set; }
        public Nullable<decimal> ReservesCondensate { get; set; }
        public Nullable<decimal> ReservesAssociated { get; set; }
        public Nullable<decimal> ReservesNonAssociated { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MD_ExplorationStructure MD_ExplorationStructure { get; set; }
    }
}
