//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_ESDCDiscrepancy
    {
        public string xStructureID { get; set; }
        public string UncertaintyLevel { get; set; }
        public Nullable<decimal> CFUMOil { get; set; }
        public Nullable<decimal> CFUMCondensate { get; set; }
        public Nullable<decimal> CFUMAssociated { get; set; }
        public Nullable<decimal> CFUMNonAssociated { get; set; }
        public Nullable<decimal> CFPPAOil { get; set; }
        public Nullable<decimal> CFPPACondensate { get; set; }
        public Nullable<decimal> CFPPAAssociated { get; set; }
        public Nullable<decimal> CFPPANonAssociated { get; set; }
        public Nullable<decimal> CFWIOil { get; set; }
        public Nullable<decimal> CFWICondensate { get; set; }
        public Nullable<decimal> CFWIAssociated { get; set; }
        public Nullable<decimal> CFWINonAssociated { get; set; }
        public Nullable<decimal> CFCOil { get; set; }
        public Nullable<decimal> CFCCondensate { get; set; }
        public Nullable<decimal> CFCAssociated { get; set; }
        public Nullable<decimal> CFCNonAssociated { get; set; }
        public Nullable<decimal> UCOil { get; set; }
        public Nullable<decimal> UCCondensate { get; set; }
        public Nullable<decimal> UCAssociated { get; set; }
        public Nullable<decimal> UCNonAssociated { get; set; }
        public Nullable<decimal> CIOOil { get; set; }
        public Nullable<decimal> CIOCondensate { get; set; }
        public Nullable<decimal> CIOAssociated { get; set; }
        public Nullable<decimal> CIONonAssociated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MD_ExplorationStructure MD_ExplorationStructure { get; set; }
    }
}
