//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_ESDCInPlace
    {
        public string xStructureID { get; set; }
        public string UncertaintyLevel { get; set; }
        public Nullable<decimal> P90IOIP { get; set; }
        public Nullable<decimal> P90IGIP { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MD_ExplorationStructure MD_ExplorationStructure { get; set; }
    }
}
