//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_ESDCProd
    {
        public string xStructureID { get; set; }
        public Nullable<decimal> GCPPrevOil { get; set; }
        public Nullable<decimal> GCPPrevCondensate { get; set; }
        public Nullable<decimal> GCPPrevAssociated { get; set; }
        public Nullable<decimal> GCPPrevNonAssociated { get; set; }
        public Nullable<decimal> SCPPrevOil { get; set; }
        public Nullable<decimal> SCPPrevCondensate { get; set; }
        public Nullable<decimal> SCPPrevAssociated { get; set; }
        public Nullable<decimal> SCPPrevNonAssociated { get; set; }
        public Nullable<decimal> GCPOil { get; set; }
        public Nullable<decimal> GCPCondensate { get; set; }
        public Nullable<decimal> GCPAssociated { get; set; }
        public Nullable<decimal> GCPNonAssociated { get; set; }
        public Nullable<decimal> SCPOil { get; set; }
        public Nullable<decimal> SCPCondensate { get; set; }
        public Nullable<decimal> SCPAssociated { get; set; }
        public Nullable<decimal> SCPNonAssociated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual MD_ExplorationStructure MD_ExplorationStructure { get; set; }
    }
}
