//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMVC.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_ESDCForecast
    {
        public string xStructureID { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> TPFOil { get; set; }
        public Nullable<decimal> TPFCondensate { get; set; }
        public Nullable<decimal> TPFAssociated { get; set; }
        public Nullable<decimal> TPFNonAssociated { get; set; }
        public Nullable<decimal> SFOil { get; set; }
        public Nullable<decimal> SFCondensate { get; set; }
        public Nullable<decimal> SFAssociated { get; set; }
        public Nullable<decimal> SFNonAssociated { get; set; }
        public Nullable<decimal> CIOOil { get; set; }
        public Nullable<decimal> CIOCondensate { get; set; }
        public Nullable<decimal> CIOAssociated { get; set; }
        public Nullable<decimal> CIONonAssociated { get; set; }
        public Nullable<decimal> LPOil { get; set; }
        public Nullable<decimal> LPCondensate { get; set; }
        public Nullable<decimal> LPAssociated { get; set; }
        public Nullable<decimal> LPNonAssociated { get; set; }
        public Nullable<decimal> AverageGrossHeat { get; set; }
        public string Remarks { get; set; }
    
        public virtual MD_ExplorationStructure MD_ExplorationStructure { get; set; }
    }
}
