using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SHUNetMVC.Infrastructure.EntityFramework.Queries
{
    public class TXProsResourcesTargetQuery : BaseCrudQuery
    {
        public override string SelectPagedQuery => @"
            SELECT pt.TargetID,
                  pt.TargetName,
                  pt.xStructureID,
                  pt.P90InPlaceOil,
                  pt.P90InPlaceOilUoM,
                  pt.P50InPlaceOil,
                  pt.P50InPlaceOilUoM,
                  pt.PMeanInPlaceOil,
                  pt.PMeanInPlaceOilUoM,
                  pt.P10InPlaceOil,
                  pt.P10InPlaceOilUoM,
                  pt.P90InPlaceGas,
                  pt.P90InPlaceGasUoM,
                  pt.P50InPlaceGas,
                  pt.P50InPlaceGasUoM,
                  pt.PMeanInPlaceGas,
                  pt.PMeanInPlaceGasUoM,
                  pt.P10InPlaceGas,
                  pt.P10InPlaceGasUoM,
                  pt.P90InPlaceTotal,
                  pt.P90InPlaceTotalUoM,
                  pt.P50InPlaceTotal,
                  pt.P50InPlaceTotalUoM,
                  pt.PMeanInPlaceTotal,
                  pt.PMeanInPlaceTotalUoM,
                  pt.P10InPlaceTotal,
                  pt.P10InPlaceTotalUoM,
                  pt.P90RecoverableOil,
                  pt.P90RecoverableOilUoM,
                  pt.P50RecoverableOil,
                  pt.P50RecoverableOilUoM,
                  pt.PMeanRecoverableOil,
                  pt.PMeanRecoverableOilUoM,
                  pt.P10RecoverableOil,
                  pt.P10RecoverableOilUoM,
                  pt.P90RecoverableGas,
                  pt.P90RecoverableGasUoM,
                  pt.P50RecoverableGas,
                  pt.P50RecoverableGasUoM,
                  pt.PMeanRecoverableGas,
                  pt.PMeanRecoverableGasUoM,
                  pt.P10RecoverableGas,
                  pt.P10RecoverableGasUoM,
                  pt.P90RecoverableTotal,
                  pt.P90RecoverableTotalUoM,
                  pt.P50RecoverableTotal,
                  pt.P50RecoverableTotalUoM,
                  pt.PMeanRecoverableTotal,
                  pt.PMeanRecoverableTotalUoM,
                  pt.P10RecoverableTotal,
                  pt.P10RecoverableTotalUoM,
                  pt.HydrocarbonTypeParID,
                  pt.GCFSR,
                  pt.GCFSRUoM,
                  pt.GCFTM,
                  pt.GCFTMUoM,
                  pt.GCFReservoir,
                  pt.GCFReservoirUoM,
                  pt.GCFClosure,
                  pt.GCFClosureUoM,
                  pt.GCFContainment,
                  pt.GCFContainmentUoM,
                  pt.GCFPGTotal,
                  pt.GCFPGTotalUoM,
                  pt.CreatedDate,
                  pt.CreatedBy
              FROM xplore.TX_ProsResourcesTarget pt";

        public override string PagedRoles => @"
            SELECT  s.xStructureID,
                    s.xStructureName,
                    s.xStructureStatusParID,
                    s.SingleOrMultiParID,
                    s.ExplorationTypeParID,
                    pl.ParamValue1Text,
                    ba.BasinID,
                    ba.BasinName,
                    s.RegionalID,
                    s.ZonaID,
                    s.APHID,
                    a.xAssetID,
                    a.xAssetName,
                    bl.xBlockID,
                    bl.xBlockName,
                    s.UDClassificationParID,
                    s.UDSubClassificationParID,
                    s.UDSubTypeParID,
                    s.ExplorationAreaParID,
                    s.CountriesID,
                    s.Play,
                    s.StatusData,
                    s.CreatedDate,
                    s.CreatedBy
                FROM dbo.MD_ExplorationStructure s
                LEFT JOIN dbo.MD_ParamaterList pl on s.xStructureStatusParID = pl.ParamListID
                LEFT JOIN dbo.MD_ExplorationAsset a on s.xAssetID = a.xAssetID
                LEFT JOIN dbo.MD_ExplorationBasin ba on s.BasinID = ba.BasinID
                LEFT JOIN dbo.MD_ExplorationBlock bl on s.xBlockID = bl.xBlockID
                WHERE pl.ParamID = 'ExplorationStructureStatus' AND s.StatusData = 'Draft'";

        public override string CountQuery => @"
            select count(1) from xplore.TX_ProsResourcesTarget pt";

        public override string GenerateID => @"select TOP 1 TargetID from xplore.TX_ProsResourcesTarget order by TargetID desc";

        public override string LookupTextQuery => @"select pt.TargetName from xplore.TX_ProsResourcesTarget pt";
        public override string LookupListTextQuery => @"
            SELECT pt.TargetID,
                  pt.TargetName,
                  pt.xStructureID,
                  pt.P90InPlaceOil,
                  pt.P90InPlaceOilUoM,
                  pt.P50InPlaceOil,
                  pt.P50InPlaceOilUoM,
                  pt.PMeanInPlaceOil,
                  pt.PMeanInPlaceOilUoM,
                  pt.P10InPlaceOil,
                  pt.P10InPlaceOilUoM,
                  pt.P90InPlaceGas,
                  pt.P90InPlaceGasUoM,
                  pt.P50InPlaceGas,
                  pt.P50InPlaceGasUoM,
                  pt.PMeanInPlaceGas,
                  pt.PMeanInPlaceGasUoM,
                  pt.P10InPlaceGas,
                  pt.P10InPlaceGasUoM,
                  pt.P90InPlaceTotal,
                  pt.P90InPlaceTotalUoM,
                  pt.P50InPlaceTotal,
                  pt.P50InPlaceTotalUoM,
                  pt.PMeanInPlaceTotal,
                  pt.PMeanInPlaceTotalUoM,
                  pt.P10InPlaceTotal,
                  pt.P10InPlaceTotalUoM,
                  pt.RFOil,
                  pt.RFGas,
                  pt.P90RecoverableOil,
                  pt.P90RecoverableOilUoM,
                  pt.P50RecoverableOil,
                  pt.P50RecoverableOilUoM,
                  pt.PMeanRecoverableOil,
                  pt.PMeanRecoverableOilUoM,
                  pt.P10RecoverableOil,
                  pt.P10RecoverableOilUoM,
                  pt.P90RecoverableGas,
                  pt.P90RecoverableGasUoM,
                  pt.P50RecoverableGas,
                  pt.P50RecoverableGasUoM,
                  pt.PMeanRecoverableGas,
                  pt.PMeanRecoverableGasUoM,
                  pt.P10RecoverableGas,
                  pt.P10RecoverableGasUoM,
                  pt.P90RecoverableTotal,
                  pt.P90RecoverableTotalUoM,
                  pt.P50RecoverableTotal,
                  pt.P50RecoverableTotalUoM,
                  pt.PMeanRecoverableTotal,
                  pt.PMeanRecoverableTotalUoM,
                  pt.P10RecoverableTotal,
                  pt.P10RecoverableTotalUoM,
                  pt.HydrocarbonTypeParID,
                  pt.GCFSR,
                  pt.GCFSRUoM,
                  pt.GCFTM,
                  pt.GCFTMUoM,
                  pt.GCFReservoir,
                  pt.GCFReservoirUoM,
                  pt.GCFClosure,
                  pt.GCFClosureUoM,
                  pt.GCFContainment,
                  pt.GCFContainmentUoM,
                  pt.GCFPGTotal,
                  pt.GCFPGTotalUoM,
                  pt.CreatedDate,
                  pt.CreatedBy
              FROM xplore.TX_ProsResourcesTarget pt
              where pt.xStructureID = '{0}'";

        public override string PagedReport => throw new NotImplementedException();

        public override string ExcelExportQuery => @"
                SELECT pt.TargetID,
                es.xStructureID,
                es.xStructureName,
                pt.TargetName,
                pt.P90InPlaceOil,
                pt.P90InPlaceOilUoM,
                pt.P50InPlaceOil,
                pt.P50InPlaceOilUoM,
                pt.PMeanInPlaceOil,
                pt.PMeanInPlaceOilUoM,
                pt.P10InPlaceOil,
                pt.P10InPlaceOilUoM,
                pt.P90InPlaceGas,
                pt.P90InPlaceGasUoM,
                pt.P50InPlaceGas,
                pt.P50InPlaceGasUoM,
                pt.PMeanInPlaceGas,
                pt.PMeanInPlaceGasUoM,
                pt.P10InPlaceGas,
                pt.P10InPlaceGasUoM,
                pt.P90InPlaceTotal,
                pt.P90InPlaceTotalUoM,
                pt.P50InPlaceTotal,
                pt.P50InPlaceTotalUoM,
                pt.PMeanInPlaceTotal,
                pt.PMeanInPlaceTotalUoM,
                pt.P10InPlaceTotal,
                pt.P10InPlaceTotalUoM,
                pt.RFOil,
                pt.RFGas,
                pt.P90RecoverableOil,
                pt.P90RecoverableOilUoM,
                pt.P50RecoverableOil,
                pt.P50RecoverableOilUoM,
                pt.PMeanRecoverableOil,
                pt.PMeanRecoverableOilUoM,
                pt.P10RecoverableOil,
                pt.P10RecoverableOilUoM,
                pt.P90RecoverableGas,
                pt.P90RecoverableGasUoM,
                pt.P50RecoverableGas,
                pt.P50RecoverableGasUoM,
                pt.PMeanRecoverableGas,
                pt.PMeanRecoverableGasUoM,
                pt.P10RecoverableGas,
                pt.P10RecoverableGasUoM,
                pt.P90RecoverableTotal,
                pt.P90RecoverableTotalUoM,
                pt.P50RecoverableTotal,
                pt.P50RecoverableTotalUoM,
                pt.PMeanRecoverableTotal,
                pt.PMeanRecoverableTotalUoM,
                pt.P10RecoverableTotal,
                pt.P10RecoverableTotalUoM,
                pt.HydrocarbonTypeParID,
                pt.GCFSR,
                pt.GCFSRUoM,
                pt.GCFTM,
                pt.GCFTMUoM,
                pt.GCFReservoir,
                pt.GCFReservoirUoM,
                pt.GCFClosure,
                pt.GCFClosureUoM,
                pt.GCFContainment,
                pt.GCFContainmentUoM,
                pt.GCFPGTotal,
                pt.GCFPGTotalUoM,
                pt.CreatedDate
                FROM xplore.TX_ProsResourcesTarget pt
                JOIN dbo.MD_ExplorationStructure es on pt.xStructureID = es.xStructureID
                where pt.xStructureID = '{0}'";
    }
}
